### ISSUE TITLE
Feature request: Add the ability to pass "ignore" for hadolint

### ISSUE THREAD

**Issue by jecnua** [reviewdog/action-hadolint#19]
Hi all.

I think a good feature to add would be to allow the injection of "ignore codes" when calling hadolint.
For my usecases I had to rebuilt and container and then add in the call:

```
[...]
          git ls-files --exclude='Dockerfile*' --ignored | xargs hadolint ${HADOLINT_IGNORES} \
          | reviewdog -efm="%f:%l %m" \
[...]
```

where HADOLINT_IGNORES is (in ENV):

`HADOLINT_IGNORES: "--ignore DL3009 --ignore DL3008"`

This is not perfect since the user needs to add the flags too, but I hope it helps convein the point.
Thanks you so much for the action and the work until now.

**Comment by adnikiforov** [comment]
I'll take this.
