### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by benregn** [reviewdog/action-hadolint#33]
I'm trying to run this action using the provided example workflow in the README but I get an error when my workflow runs. I have reproduced the error in an [example repo](https://github.com/benregn/reviewdog-hadolint-action-problem). The error can be seen in [this check](https://github.com/benregn/reviewdog-hadolint-action-problem/pull/1/checks?check_run_id=1556173590#step:4:13).

Side note: If I don't supply the `exclude` option, I get this error `fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths`. Not sure if related.

**Comment by mgrachev** [comment]
I'm sorry for the long response. I have fixed this error. Can you try it again?
