### ISSUE TITLE
Failed to unmarshal rdjson (DiagnosticResult)

### ISSUE THREAD

**Issue by jeffoverflow** [reviewdog/action-hadolint#47]
I get an error when my workflow runs. I have reproduced the behavior.

https://github.com/reviewdog/action-hadolint/runs/2185212575

![image](https://user-images.githubusercontent.com/24581746/112428135-a989c300-8d75-11eb-87a5-2fd24a527176.png)

**Comment by mgrachev** [comment]
@haya14busa What do you think about this erro?

**Comment by singhprd** [comment]
I think this is probably caused by the upgrade from Hadolint v1.23.0 to v2.0.0 in this PR here:
https://github.com/reviewdog/action-hadolint/pull/46

Looks like you'll need a quick rollback, then take another look at that version upgrade? 👍

**Comment by mgrachev** [comment]
I have rolled back hadolint update in v1.17.1.

**Comment by haya14busa** [comment]
It was actually caused by #588 and now it seems to be fixed.

**Comment by opeik** [comment]
This is still broken for me while using the `@v1` tag, should I be specifying a minor and patch version?

**Comment by mgrachev** [comment]
@opeik Could you create a test project to reproduce an error?
