### ISSUE TITLE
Fails on latest ubuntu-20 image

### ISSUE THREAD

**Issue by tesharp** [reviewdog/action-hadolint#54]
After update to version 20210614.1 of ubuntu 20.04 image, which has git 2.34.0 installed it fails with following error message:

```
fatal: ls-files -i must be used with either -o or -c
parse error: Invalid numeric literal at line 1, column 7
reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:1): unexpected token
```

Not running successfully on `ubuntu-latest` now

**Comment by Tarun-S** [comment]
Also having this issue. It's difficult to work around, as we can't pin old image versions in GitHub virtual environments. Also, this affects both the Ubuntu and MacOS images.

**Comment by odannyc** [comment]
Also running into this issue on latest version. Error:

```
  fatal: ls-files -i must be used with either -o or -c
  parse error: Invalid numeric literal at line 1, column 7
  reviewdog: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:1): unexpected token 
```

**Comment by mgrachev** [comment]
Hi there!

Can you test the new version of action-hadolint v1.20.1? Does it work?

**Comment by Tarun-S** [comment]
@mgrachev Yep, can confirm that this version is working now. Thanks for letting us know!

**Comment by mgrachev** [comment]
Thank you for your feedback 👍
