### ISSUE TITLE
jq: not found

### ISSUE THREAD

**Issue by horkko** [reviewdog/action-hadolint#67]
Hi,

I've been using your action to check Dockerfile. To do this we're using self-hosted runners. If `jq` is not installed on the runner(s), hadoling action throws this error: `jq: not found`

I think it should be good to have a `prerequisites` to have `jq` installed on `self-hosted` runner(s)?

Thanks

Emmanuel

**Comment by javierjulio** [comment]
I'm not sure why this would be required unless you mean documentation by prerequisites. I use self hosted runners with this action and it works fine as my understanding is that jq is included as part of the setup already. If it would help to call out on the README that jq is required, please feel free to open a PR. Thank you.
